# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Charge.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x43harge.proto\"\x18\n\tIdRequest\x12\x0b\n\x03idx\x18\x01 \x01(\x05\"\x1b\n\x0b\x44\x61teRequest\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\"\x1d\n\x0cGenreRequest\x12\r\n\x05genre\x18\x01 \x01(\t\"\\\n\rChargeRequest\x12\x0b\n\x03idx\x18\x01 \x01(\x05\x12\x0c\n\x04\x63ost\x18\x02 \x01(\x03\x12\r\n\x05genre\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x04 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\"\x0c\n\nAllRequest\"\x19\n\tCostReply\x12\x0c\n\x04\x63ost\x18\x01 \x01(\x03\"\x1e\n\x0bStringReply\x12\x0f\n\x07message\x18\x01 \x01(\t2\xeb\x03\n\x07\x43harger\x12+\n\rGetChargeById\x12\n.IdRequest\x1a\x0c.StringReply\"\x00\x12\x31\n\x0fGetChargeByDate\x12\x0c.DateRequest\x1a\x0c.StringReply\"\x00\x30\x01\x12\x33\n\x10GetChargeByGenre\x12\r.GenreRequest\x1a\x0c.StringReply\"\x00\x30\x01\x12+\n\x0e\x43urrentCostSum\x12\x0b.AllRequest\x1a\n.CostReply\"\x00\x12-\n\x0cGetChargeAll\x12\x0b.AllRequest\x1a\x0c.StringReply\"\x00\x30\x01\x12,\n\nPostCharge\x12\x0e.ChargeRequest\x1a\x0c.StringReply\"\x00\x12+\n\tPutCharge\x12\x0e.ChargeRequest\x1a\x0c.StringReply\"\x00\x12-\n\x0bPatchCharge\x12\x0e.ChargeRequest\x1a\x0c.StringReply\"\x00\x12\x32\n\x10\x44\x65leteChargeById\x12\x0e.ChargeRequest\x1a\x0c.StringReply\"\x00\x12\x31\n\x0f\x44\x65leteChargeAll\x12\x0e.ChargeRequest\x1a\x0c.StringReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Charge_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_IDREQUEST']._serialized_start=16
  _globals['_IDREQUEST']._serialized_end=40
  _globals['_DATEREQUEST']._serialized_start=42
  _globals['_DATEREQUEST']._serialized_end=69
  _globals['_GENREREQUEST']._serialized_start=71
  _globals['_GENREREQUEST']._serialized_end=100
  _globals['_CHARGEREQUEST']._serialized_start=102
  _globals['_CHARGEREQUEST']._serialized_end=194
  _globals['_ALLREQUEST']._serialized_start=196
  _globals['_ALLREQUEST']._serialized_end=208
  _globals['_COSTREPLY']._serialized_start=210
  _globals['_COSTREPLY']._serialized_end=235
  _globals['_STRINGREPLY']._serialized_start=237
  _globals['_STRINGREPLY']._serialized_end=267
  _globals['_CHARGER']._serialized_start=270
  _globals['_CHARGER']._serialized_end=761
# @@protoc_insertion_point(module_scope)
